#!/usr/bin/env bash
# Vendor the header-only ROCm libraries the HIP extensions need.
#
#   ./prepare_rocm_headers.sh
#
# Idempotent — safe to re-run. Already done once; this exists so the step is
# reproducible rather than a pile of manual commands.
#
# Why this is needed
# ------------------
# Two extensions include headers that are NOT packaged in the 'ROCm for Radeon'
# apt repo this machine uses (repo.radeon.com/rocmradeon/apt/26.13). That repo
# is runtime-focused and ships no rocThrust / hipCUB / rocPRIM at all:
#
#   diff-gaussian-rasterization/hip_rasterizer/rasterizer_impl.hip
#       -> hipcub/hipcub.hpp, thrust/device_ptr.h, thrust/scan.h
#   torchsparse/torchsparse/backend/devoxelize/devoxelize_hip.hip
#       -> thrust/device_vector.h
#
# All three are header-only, so cloning them is sufficient — nothing to compile
# or install. hipCUB and rocThrust are both implemented on top of rocPRIM,
# which is why all three are required.
#
# The one wrinkle: each library's <lib>_version.hpp is generated by CMake from a
# .hpp.in template, and the headers #include it. Since we are not running CMake,
# we substitute the placeholders ourselves from VERSION_STRING in each
# CMakeLists.txt.

set -euo pipefail

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Matches the ROCm 7.x series of the installed runtime (7.14). These are
# header-only and API-stable across 7.x, and are verified to compile with the
# system's HIP 7.14 / clang 23 toolchain.
ROCM_TAG="rocm-7.2.4"
DEST=".rocm-headers"

mkdir -p "${DEST}"

echo "=============================================="
echo "  Vendoring ROCm header-only libs (${ROCM_TAG})"
echo "=============================================="
echo

for repo in rocPRIM rocThrust hipCUB; do
    if [[ -d "${DEST}/${repo}/.git" ]]; then
        echo "[clone] ${repo} already present — skipping"
    else
        echo "[clone] ${repo} @ ${ROCM_TAG}"
        git clone --depth 1 --branch "${ROCM_TAG}" \
            "https://github.com/ROCm/${repo}.git" "${DEST}/${repo}" --quiet
    fi
done
echo

# --- generate the CMake-templated version headers --------------------------
# VERSION_NUMBER convention: major*100000 + minor*100 + patch
gen_version() {
    local template="$1" out="$2" prefix="$3" cmakelists="$4"

    local vs major minor patch number
    vs="$(grep -oE 'set\(VERSION_STRING +"[0-9]+\.[0-9]+\.[0-9]+"' "${cmakelists}" \
          | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
    if [[ -z "${vs}" ]]; then
        echo "ERROR: could not read VERSION_STRING from ${cmakelists}" >&2
        exit 1
    fi
    IFS='.' read -r major minor patch <<<"${vs}"
    number=$(( major * 100000 + minor * 100 + patch ))

    sed -e "s/@${prefix}_VERSION_MAJOR@/${major}/g" \
        -e "s/@${prefix}_VERSION_MINOR@/${minor}/g" \
        -e "s/@${prefix}_VERSION_PATCH@/${patch}/g" \
        -e "s/@${prefix}_VERSION_NUMBER@/${number}/g" \
        "${template}" > "${out}"

    if grep -qE '@[A-Za-z_]+@' "${out}"; then
        echo "ERROR: unsubstituted CMake placeholders remain in ${out}:" >&2
        grep -oE '@[A-Za-z_]+@' "${out}" | sort -u >&2
        exit 1
    fi
    echo "[version] ${out}  (v${vs} -> ${number})"
}

gen_version "${DEST}/rocPRIM/rocprim/include/rocprim/rocprim_version.hpp.in" \
            "${DEST}/rocPRIM/rocprim/include/rocprim/rocprim_version.hpp" \
            rocprim "${DEST}/rocPRIM/CMakeLists.txt"

gen_version "${DEST}/rocThrust/thrust/rocthrust_version.hpp.in" \
            "${DEST}/rocThrust/thrust/rocthrust_version.hpp" \
            rocthrust "${DEST}/rocThrust/CMakeLists.txt"

gen_version "${DEST}/hipCUB/hipcub/include/hipcub/hipcub_version.hpp.in" \
            "${DEST}/hipCUB/hipcub/include/hipcub/hipcub_version.hpp" \
            hipcub "${DEST}/hipCUB/CMakeLists.txt"
echo

# --- unified include prefix ------------------------------------------------
# The three repos have differently-shaped layouts; collapse them into one
# directory that can go straight onto CPLUS_INCLUDE_PATH (see env_amd.sh).
mkdir -p "${DEST}/include"
ln -sfn ../rocPRIM/rocprim/include/rocprim "${DEST}/include/rocprim"
ln -sfn ../rocThrust/thrust               "${DEST}/include/thrust"
ln -sfn ../hipCUB/hipcub/include/hipcub   "${DEST}/include/hipcub"

echo "[verify] include prefix: ${DEST}/include"
fail=0
for h in rocprim/rocprim.hpp rocprim/rocprim_version.hpp \
         thrust/scan.h thrust/device_vector.h thrust/rocthrust_version.hpp \
         hipcub/hipcub.hpp hipcub/hipcub_version.hpp
do
    if [[ -e "${DEST}/include/${h}" ]]; then
        echo "           OK      ${h}"
    else
        echo "           MISSING ${h}" >&2
        fail=1
    fi
done
[[ ${fail} -eq 0 ]] || exit 1

echo
echo "Done. env_amd.sh puts ${DEST}/include on CPLUS_INCLUDE_PATH."
